import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/app/components/Header";
import { selectChains } from "@/lib/database";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({ children }: { children: React.ReactNode }) => {
  const chains = (await selectChains()).map(({ name }) => name);
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="px-16 bg-gradient-to-r from-black to-neutral-800">
          <Header chains={chains} />
          <div>{children}</div>
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
